//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04_Data.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Disco()
        {
            this.Tema = new HashSet<Tema>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_discografia { get; set; }
        public Nullable<int> id_autor { get; set; }
        public int id_categoria { get; set; }
        public string nombre { get; set; }
        public string imagen { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Discografica Discografica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tema> Tema { get; set; }
    }
}
